name: live_activities_example
description: Demonstrates how to use the live_activities plugin.
publish_to: "none"

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  live_activities: ^2.0.0+2
  background_task: ^0.2.0+2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
